theme: jekyll-theme-chirpy

lang: vi-VN

timezone: Asia/Ho_Chi_Minh

title: Thổ địa Dĩ An

tagline: Nơi bạn thỏa sức khám phá Dĩ An!

description: >-
  Thổ Địa Dĩ An chia sẻ địa điểm ăn uống, quán cafe, du lịch, giải trí và tin tức mới nhất tại Dĩ An và Bình Dương.

url: 'https://thodiadian.com'

github:
  username: thodiadian

social:
  name: thổ địa Dĩ An
  email: hieukhongprovipno1@gmail.com
  links:
    - https://github.com/thodiadian

webmaster_verifications:
  google: jzH4X1KaTepEZ3eUse49KWpY2jy-Nx5BacPM32Zij28

analytics:
  google:
    id: G-555T8X96SK

avatar: /assets/images/avatar.png

toc: true

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths: []

paginate: 10

baseurl: ""

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:categories/:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
